### ISSUE TITLE
downloadFile function is not working on Capacitor 3

### ISSUE THREAD

**Issue by najmulansari** [capacitor-community/http#142]
Hi There,
downloadFile() function is not working on Capacitor 3

It was working fine with Capacitor 2, but it started failing after upgrading to Capacitor 3. Please see the below screenshot.

**Screenshots**
![image](https://user-images.githubusercontent.com/10203537/124368577-666ea400-dc30-11eb-814b-8a0109f97a89.png)

I am testing this on Android 10.

Please look into the issue. Thanks for your help.

**Comment by visiblesoft-org** [comment]
As issue https://github.com/capacitor-community/http/issues/135#issuecomment-868846620 states, just add the method to your downloadFile call.

Example:
method: 'GET|POST|etc'

Regards

**Comment by najmulansari** [comment]
I tried adding method in options but now getting "IO Error". I am using the below code.

![image](https://user-images.githubusercontent.com/10203537/124411783-2f28f180-dd1b-11eb-9d8f-61ac81058c76.png)


Below error, I am getting.

![image](https://user-images.githubusercontent.com/10203537/124411669-f8eb7200-dd1a-11eb-80b9-cfd509970086.png)

Please let me know if I am doing anything wrong.

**Comment by thomasvidas** [comment]
Can you provide a small github repo that is reproduction of your bug?

**Comment by najmulansari** [comment]
Hi @thomasvidas,
Please find a test repo from here
https://github.com/najmulansari/samplebook/tree/master

**Comment by baio** [comment]
Hi ! The same error here !

**Comment by najmulansari** [comment]
Any update on this yet. I am still stuck with this and not able to go ahead with the capacitor upgrade. Please help.

**Comment by sla100** [comment]
There is a Java stack:
```
java.io.FileNotFoundException: https://example.com/
        at com.android.okhttp.internal.huc.HttpURLConnectionImpl.getInputStream(HttpURLConnectionImpl.java:255)
        at com.android.okhttp.internal.huc.DelegatingHttpsURLConnection.getInputStream(DelegatingHttpsURLConnection.java:211)
        at com.android.okhttp.internal.huc.HttpsURLConnectionImpl.getInputStream(HttpsURLConnectionImpl.java:30)
        at com.getcapacitor.plugin.http.CapacitorHttpUrlConnection.getInputStream(CapacitorHttpUrlConnection.java:339)
        at com.getcapacitor.plugin.http.HttpRequestHandler.downloadFile(HttpRequestHandler.java:430)
        at com.getcapacitor.plugin.http.Http.downloadFile(Http.java:159)
```

**Comment by elvisgraho** [comment]
Have IO Error on android too

**Comment by elvisgraho** [comment]
`ts
      const httpOptions: HttpDownloadFileOptions = {
        url: normalImageUrlThatWorksOnIOS
        fileDirectory: Directory.Cache,
        filePath: normalImageNameThatWorksOnIOS,
      };
      const resp = await Http.downloadFile(httpOptions);
```

Getting - IO Error

Error jumps to the code line
```
                    const storedCall = callbacks.get(result.callbackId);
                    if (storedCall) {
                        // looks like we've got a stored call
                        if (result.error) {
                            // ensure stacktraces by copying error properties to an Error
                            result.error = Object.keys(result.error).reduce((err, key) => {
                                // use any type to avoid importing util and compiling most of .ts files
                                err[key] = result.error[key];
                                return err;
                            }, new cap.Exception(''));
                        }
                        if (typeof storedCall.callback === 'function') {
                            // callback <----- here ist he error line for me
                            if (result.success) {
                                storedCall.callback(result.data);
                            }
                            else {
                                storedCall.callback(null, result.error);
                            }
                        }
```

**Comment by fmichael** [comment]
If it helps anyone, I managed to solve the IO error while downloading files on Android using capacitor 3 (that worked fine on iOS).

My specific issue was that I was attempting to download a file to a sub folder without having created the sub folder first.
Apparently the http.downloadFile does not have a built in logic or flag to enable recurssive mode, the way Capacitor Filesystem does.

It was erroring out for me in the java side; `HttpRequestHandler.java` while trying to create the `new FileOutputStream()`.

Example:
```
Http.downloadFile({
     filePath: "test/video.mp4",
     fileDirectory: Directory.Data,
     method: "GET",
     url: "..."
})
```
this would fail and return `IO Error`.
Once I added a mkdir before attempting download, it worked fine.
```
await Filesystem.mkdir({
    path: "test",
    directory: Directory.Data
})

await Http.downloadFile({
     filePath: "test/video.mp4",
     fileDirectory: Directory.Data,
     method: "GET",
     url: "..."
})
```

**Comment by elvisgraho** [comment]
Making dir beforehand doesn't solve IO Error for me. Im on Android 9

**Comment by ericmoolin** [comment]
I am also getting the IO error, creating the directory beforehand did not resolve it for me either. When I check the directory, the files have been created, so the IO error is happening after that process.

**Comment by nikage** [comment]
I've got this error in android logs:
```
V/Capacitor/Http: Permission 'android.permission.WRITE_EXTERNAL_STORAGE' is granted
E/Capacitor/Plugin: IO Error
    java.io.FileNotFoundException: /storage/emulated/0/Download/1640096041184_Calm.ogg: open failed: EACCES (Permission denied)
        at libcore.io.IoBridge.open(IoBridge.java:496)
        at java.io.FileOutputStream.<init>(FileOutputStream.java:235)
        at com.getcapacitor.plugin.http.HttpRequestHandler.downloadFile(HttpRequestHandler.java:438)
        at com.getcapacitor.plugin.http.Http.downloadFile(Http.java:167)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.getcapacitor.PluginHandle.invoke(PluginHandle.java:121)
        at com.getcapacitor.Bridge.lambda$callPluginMethod$0$Bridge(Bridge.java:592)
        at com.getcapacitor.Bridge$$ExternalSyntheticLambda5.run(Unknown Source:8)
        at android.os.Handler.handleCallback(Handler.java:883)
        at android.os.Handler.dispatchMessage(Handler.java:100)
        at android.os.Looper.loop(Looper.java:214)
        at android.os.HandlerThread.run(HandlerThread.java:67)
```
I've figured out that you can use "DOWNLOADS" as forlder on Android 11+ but on android 10 throws the above error.

**Comment by ericmoolin** [comment]
> I am also getting the IO error, creating the directory beforehand did not resolve it for me either.

Just wanted to follow up and say the IO Error I was getting was an interrupt to the IO Stream, which was caused by me trying to run Http.downloadFile() multiple times asynchronously.

**Comment by imclaudiafCC** [comment]
Hi everybody!
Is there a follow up to this issue? I'm still getting the IO Error

**Comment by ericmoolin** [comment]
> Hi everybody! Is there a follow up to this issue? I'm still getting the IO Error

Try running your application outside of the android studio emulator. I found the error was only present in the emulator.

**Comment by elvisgraho** [comment]
@ericmoolin  im not sure if it is the case. The emulator Android version must match with the live device. It can be the case of - my real device has different Android version and I no longer encounter issues that I have on emulators.

**Comment by hommalex** [comment]
Any news on that.
On Android 12:
IO message if I use Directory.Downloads
Unable to open directory: when I use Directory.Data

It's defo a permission issue. 

Anybody would have a solution to open PDF. 
Browser just downloads the file, it doesn't open it.

Thanks.

**Comment by nikage** [comment]
> I've figured out that you can use "DOWNLOADS" as forlder on Android 11+ but on android 10 throws the above error.
I've used this package https://github.com/agorapulse/capacitor-mediastore for Android 10 and lower as a workaround.

**Comment by nikage** [comment]
> IO message if I use Directory.Downloads
>> I've figured out that you can use "DOWNLOADS" as folder on Android 11+ but on android 10 throws the above error.
"DOWNLOADS" is not in documentation but I figured out from java source code and it worked for me

> Anybody would have a solution to open PDF.
Although it's not quite relevant to this issue, I tried https://ionicframework.com/docs/native/file-opener and it works for Capacitor 3 as well 

> Browser just downloads the file, it doesn't open it.
it doesn't have to, IMHO.

**Comment by tylerclark** [comment]
I too have been having issues with `downloadFile` on Android only. I have opened a [separate issue](https://github.com/capacitor-community/http/issues/266) which describes more of my problem.
