### ISSUE TITLE
Bug on Android when we want to get json data from server which send an integer

### ISSUE THREAD

**Issue by lamieltoch** [capacitor-community/http#211]
**Describe the bug**
The bug happens on android when we want to get json data from server which send an integer

**To Reproduce**
Make a http get request from client, and send an integer json value from server.

**Expected behavior**
We expect no jsonexception raised

**Screenshots**
org.json.JSONException: Value 5100 of type java.lang.Integer cannot be converted to JSONArray
        at org.json.JSON.typeMismatch(JSON.java:112)
        at org.json.JSONArray.<init>(JSONArray.java:98)
        at org.json.JSONArray.<init>(JSONArray.java:110)
        at com.getcapacitor.JSArray.<init>(JSArray.java:16)
        at com.getcapacitor.plugin.http.HttpRequestHandler.parseJSON(HttpRequestHandler.java:312)
        at com.getcapacitor.plugin.http.HttpRequestHandler.readData(HttpRequestHandler.java:239)
        at com.getcapacitor.plugin.http.HttpRequestHandler.buildResponse(HttpRequestHandler.java:209)
        at com.getcapacitor.plugin.http.HttpRequestHandler.request(HttpRequestHandler.java:401)
        at com.getcapacitor.plugin.http.Http$1.run(Http.java:83)
        at java.lang.Thread.run(Thread.java:919)

**Desktop (please complete the following information):**
Android emulator api 29

**Smartphone (please complete the following information):**
 Android emulator api 29

**Additional context**

**Comment by lamieltoch** [comment]
Hi, I the file "HttpRequestHandler.java", If I put at line 308 try {
                        return new JSArray(input);
                    }
                    catch(JSONException e2) {
                        return Integer.parseInt(input.trim());
                    }

It seems to work for Integer send by the server.

So may you put this piece of code in main branch of the code.

Regards

Lamiel
