### ISSUE TITLE
JSON-Response null: value null of type org.json.jsonobject$1 cannot be converted to jsonobject

### ISSUE THREAD

**Issue by stonewoodman** [capacitor-community/http#89]
**Describe the bug**
When I do a HTTP request and the response is a json value null, then throws a exception

**Versions**
@capacitor/core@2.4.6
@capacitor/android@2.4.6
@capacitor-community/http@0.2.1

**To Reproduce**
1. Call request to an webserver
2. Result from webserver is null
4. See error in Android Studio or Chrome Debugger

**Expected behavior**
Attribute data in result object is a null-value

**Smartphone:**
 - Device: Samsung S10
 - OS: Android

**Additional context**
```E/Capacitor/Plugin: Error
    org.json.JSONException: Value null of type org.json.JSONObject$1 cannot be converted to JSONArray
        at org.json.JSON.typeMismatch(JSON.java:112)
        at org.json.JSONArray.<init>(JSONArray.java:98)
        at org.json.JSONArray.<init>(JSONArray.java:110)
        at com.getcapacitor.JSArray.<init>(JSArray.java:17)
        at com.getcapacitor.plugin.http.Http.buildResponse(Http.java:394)
        at com.getcapacitor.plugin.http.Http.get(Http.java:83)
        at com.getcapacitor.plugin.http.Http.request(Http.java:64)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.getcapacitor.PluginHandle.invoke(PluginHandle.java:99)
        at com.getcapacitor.Bridge$1.run(Bridge.java:542)
        at android.os.Handler.handleCallback(Handler.java:883)
        at android.os.Handler.dispatchMessage(Handler.java:100)
        at android.os.Looper.loop(Looper.java:237)
        at android.os.HandlerThread.run(HandlerThread.java:67)
```

But the originally exception throws at Http.java:391
`org.json.JSONException: Value null of type org.json.JSONObject$1 cannot be converted to JSONObject`

**Comment by thomasvidas** [comment]
Fixed in #90
