### ISSUE TITLE
Husky throws when installing

### ISSUE THREAD

**Issue by muuvmuuv** [capacitor-community/http#97]
**Describe the bug**

Installing throws husky error cannot find package `please-upgrade-node`.

**To Reproduce**

**Expected behavior**

**Screenshots**

```
> husky@4.3.7 preuninstall .../node_modules/@capacitor-community/http/node_modules/husky
> node husky uninstall

internal/modules/cjs/loader.js:883
  throw err;
  ^

Error: Cannot find module 'please-upgrade-node'
Require stack:
- /Users/marvin/Development/M8FINDER/APP/patches/http/node_modules/husky/husky.js
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:880:15)
    at Function.Module._load (internal/modules/cjs/loader.js:725:27)
    at Module.require (internal/modules/cjs/loader.js:952:19)
    at require (internal/modules/cjs/helpers.js:88:18)
    at Object.<anonymous> (/Users/marvin/Development/M8FINDER/APP/patches/http/node_modules/husky/husky.js:3:27)
    at Module._compile (internal/modules/cjs/loader.js:1063:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1092:10)
    at Module.load (internal/modules/cjs/loader.js:928:32)
    at Function.Module._load (internal/modules/cjs/loader.js:769:14)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:72:12) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    '/Users/marvin/Development/M8FINDER/APP/patches/http/node_modules/husky/husky.js'
  ]
}
npm WARN lifecycle husky@4.3.7~preuninstall: continuing anyway husky@4.3.7 preuninstall: `node husky uninstall`
npm WARN lifecycle Exit status 1
```

**Desktop (please complete the following information):**
 - OS: [e.g. iOS] macOS Big Sur on Silicon
 - Browser [e.g. chrome, safari] Terminal
 - Version [e.g. 22] latest

**Smartphone (please complete the following information):**

**Additional context**

Maybe remove husky in favour of [Lefthook](https://github.com/Arkweid/lefthook).

**Comment by thomasvidas** [comment]
What version of `npm` and `node` are you on? I cannot reproduce with npm 6. However, I know npm 7 broke a lot of peerDependency things and this may be related

**Comment by muuvmuuv** [comment]
Running Node v14.15.4 and npm 6.14.10 with [Volta](https://volta.sh/). But I had this issue with other packages too where Husky just called "uninstall" instead when not installed directly. I really don't know why it is doing it anyway since it's a dev dependency, it shouldn't be installed anyway?

**Comment by thomasvidas** [comment]
Can you try pulling from the `capacitor-v3` branch and trying again? I upgrade to a newer version of husky and wonder if that could fix your issue

**Comment by muuvmuuv** [comment]
Seems to work just fine again! Thanks :)
